print()
print("PANTUN 1")
print("Siang hari pulang sekolah")
print("Di tengah jalan turun hujan")
print("Walapun kita sudah berpisah")
print("Kenang di sungai tak terlupakan")
print()
print("PANTUN2")
print("Pergi ke sawah pagi-pagi")
print("Lewat jembatan pegag tali")
print("Bayang-bayanganmu selalu menghantui")
print()
print("PANTUN 3")
print("Pasukan mangga dalam kardus")
print("Untuk di bawa ke pekanbaru")
print("Walaupun kita sudah putus")
print("Aku tetep sayang padamu")
#ini adalah catatan
