print("PANTUN 1")
print("jalan-jalan ke tanjung batu")
print("melihat kamu beli mobil baru")
print("anak itik dimakan sapi")
print("tapi tetap kamu yang ada di hati")
print()
print("PANTUN 2")
print("beli ketupat bawa tongkat")
print("selamat hari jum'at")
print("buat kamu yang cakepnya")
print("gak ada obat")
print()
print("PANTUN 3")
print("ke pasar mau beli bawang")
print("sampai pasar malah beli pandan")
print("padahal aku sudah terlanjur sayang")
print("tapi kamu anggap aku teman")
#ini adalah catatan